### ISSUE TITLE
Add baseUrl configuration

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow-incubator/iglu-server#34]
Using Iglu Server behind a proxy prevents Swagger UI to load required assets since relative paths are used to load them.

While it is possible to bypass this issue by having tweaks in proxy configuration, it degrades UX of Iglu Server.

We should be able to plug Iglu Server behind a proxy and use it smoothly without a tweak.

**Comment by chuwy** [comment]
If we add a `baseUrl` with default to `/` I don't think it affects the UX?

**Comment by oguzhanunlu** [comment]
yes, `/` won't change anything, assuming we'll have a new configuration field, one can use default `/` if the server isn't deployed behind a proxy and vice versa.

**Comment by oguzhanunlu** [comment]
It could also be a boolean field where true would use a predefined path but I tend to think letting user set the path is a better option

**Comment by oguzhanunlu** [comment]
Let me share my user experience after a successful Iglu Server deployment behind proxy.

Below are the 9 endpoints that need to be configured.

Swagger UI endpoints:
- /static/swagger-ui/index.html
- /static/swagger-ui/swagger-ui.css
- /static/swagger-ui/swagger-ui-bundle.js
- /static/swagger-ui/swagger-ui-standalone-preset.js

Iglu Server endpoints:
- /api/schemas
- /api/drafts
- /api/auth
- /api/validation
- /api/meta

Introducing a `baseUrl` configuration could reduce 9 endpoint configuration to 1. It could also allow to deploy any other service serving endpoint(s) conflicting with any of the above.

IMO, `baseUrl` should be a user-defined path, not boolean with a predefined path.

**Comment by chuwy** [comment]
> IMO, baseUrl should be a user-defined path, not boolean with a predefined path.

I couldn't see what would be the point of boolean and endpoint (`(Boolean, String)`), compared to an optional string (`Option[String]`) in the first place. Former one just adds more unnecessary configuration

**Comment by oguzhanunlu** [comment]
Sorry for bad wording, I didn't mean 2 new fields `(Boolean, String)` by `boolean with a predefined path.` I meant only a single `Boolean` config field which would enable a path predefined by us inside the project. I also think that'd be unnecessary. I hope we're on the same page now.

It is a new config field `baseUrl` of type `Option[String]` then.
