### ISSUE TITLE
Fix authentication in Swagger

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow-incubator/iglu-server#36]
All endpoints requiring authentication can't be used through Swagger UI since authentication doesn't work as expected, i.e. trying any endpoint requiring authentication in any service shows that authentication header isn't added to request after entering super api key into authentication box in Swagger UI.

Swagger UI shows a cURL command each time an endpoint is used. Copy-pasting any of them into command line and adding authentication header works as expected.

**Comment by dnedev** [comment]
We have the same issues @oguzhanunlu. Did you find a workaround to get Swagger working or did you give up?

**Comment by oguzhanunlu** [comment]
Hi @dnedev , I didn't find any proper workaround to get Swagger UI working.

However, at the end of the day, Swagger UI sends HTTP requests and I switched to other HTTP clients like cURL to interact with Iglu Server.

**Comment by istreeter** [comment]
I was able to fix this by adding a `security` field to the swagger metadata.
