### ISSUE TITLE
Use sql "where" clause to list schemas for a vendor

### ISSUE THREAD

**Issue by istreeter** [snowplow-incubator/iglu-server#46]
This is the current implementation when listing schemas for a vendor/namespace/model:

1. Fetches all rows from the database schemas table and loads into memory
2. Deserializes all schemas into a Schema object.
3. Filters for schemas matching the vendor name / namespace / model

A better solution is to implement an efficient getSchemasByVendorName in the [Postgres class](https://github.com/snowplow-incubator/iglu-server/blob/1699510029fb9cf517fcc1a1d1c54cf6e034662b/src/main/scala/com/snowplowanalytics/iglu/server/storage/Postgres.scala#L39) rather than using the default provided by the [Storage class](https://github.com/snowplow-incubator/iglu-server/blob/1699510029fb9cf517fcc1a1d1c54cf6e034662b/src/main/scala/com/snowplowanalytics/iglu/server/storage/Storage.scala#L52)

**Comment by chuwy** [comment]
Hey @istreeter! 0.6.2 has been released already, I forgot to close the milestone. Moved these tickets to 1.0.0, but feel free to create 0.6.3 if you feel we're not there yet.
