### ISSUE TITLE
The endpoint does not exist

### ISSUE THREAD

**Issue by AbdelLightspeed** [snowplow-incubator/iglu-server#75]
Hello.
I am trying to test the docker version locally but for any the curl the server response is always "_**The endpoint does not exist**_":

Swagger curl:
```
curl -X 'GET' \
  'http://localhost:8080/custom/prefix/api/schemas/' \
  -H 'accept: application/json' \
  -H 'apikey: 5fb4713d-73ad-4163-93a9-2b82f0177c5b'
```
Response:
```
{
  "message": "The endpoint does not exist"
}
```
Thanks

**Comment by istreeter** [comment]
Hi @AbdelLightspeed

It looks like you have set the `swagger.baseUrl` property from the [example configuration file](https://github.com/snowplow-incubator/iglu-server/blob/0.7.0/config/config.reference.hocon#L67).  That hocon file is intended as an example only, you should not copy it directly.  It only makes sense to set that parameter if your iglu server is running behind a reverse proxy that changes the request paths.

I suggest remove the `swagger.baseUrl` from your hocon file and try again.  Hopefully the curl command will be correct after that.
